title: "UE5 MetaSoundで音を作ろう"
summary: |-
   音は見えないけど重要なコンテンツです。

    UE5から「MetaSound」という新しい高性能オーディオシステムが導入されます。

    MetaSoundではDTMソフトのように音源をUE5内で作成できます。

    プロシージャルな音作りやUE5においての音の設定についてまとめます。

    C++&BPの息抜きがてら趣味で書いている本です。
    
    現在noteの記事から移行中です。随時更新していきます。(2022/2/18)

topics: ["unrealengine", "ue5"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap_00_about
  - chapter01_about
  - chapter01_play_soundwave
  - chapter01_random
  - chapter01_modulator
  - chapter02_about
  - chapter02_play_c_sound
  - chapter02_envelope
  - chapter02_clear_sound
  - chapter02_bpm_and_tempo

