title: "UE5 BPとC++で学ぶ数学（中学3年間編）"
summary: |-
    ゲーム業界でTAをしていると度々「三角関数」といった数学的な知識が求められます。
    趣味が特にないので、「数学」が趣味になるように中学生からやり直してみます。
    
    中学3年間で学ぶ数学をUE5で再現してみます。

    この本は100％趣味で自分に教えるように書いてます。

topics: ["unrealengine", "ue5"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap_00_about
  - chap_01_create_project
  - chap_02_about
  - chap_02_positive_and_negative_numbers
  - chap_02_addition_and_subtraction
